# Generated by Django 5.2.1 on 2026-09-04 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_phone_alter_order_status_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_store_name', models.CharField(default='FreshMart Express Hub #4 - Baner', max_length=150)),
                ('dark_store_address', models.CharField(default='Plot 12, Baner High Street, Pune, Maharashtra 411045', max_length=255)),
                ('dark_store_lat', models.FloatField(default=18.559)),
                ('dark_store_lng', models.FloatField(default=73.7868)),
                ('customer_lat', models.FloatField(default=18.5685)),
                ('customer_lng', models.FloatField(default=73.7745)),
                ('rider_name', models.CharField(default='Vikram Shinde', max_length=100)),
                ('rider_phone', models.CharField(default='+91 98230 45678', max_length=20)),
                ('rider_vehicle', models.CharField(default='Ather 450X Electric (MH-12-BF-4892)', max_length=100)),
                ('rider_rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=3)),
                ('delivery_pin', models.CharField(default='4821', max_length=6)),
                ('override_stage', models.CharField(blank=True, choices=[('RECEIVED', 'Order Confirmed & Received'), ('PACKED', 'Packed at Micro-Hub'), ('ON_THE_WAY', 'Rider On The Way'), ('ARRIVING', 'Arriving at Doorstep'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], help_text='Manual override for testing simulator stages', max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='orders.order')),
            ],
        ),
    ]
