# Generated by Django 5.2.1 on 2026-09-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderdeliverytracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdeliverytracking',
            name='customer_lat',
            field=models.FloatField(default=22.729),
        ),
        migrations.AlterField(
            model_name='orderdeliverytracking',
            name='customer_lng',
            field=models.FloatField(default=75.865),
        ),
        migrations.AlterField(
            model_name='orderdeliverytracking',
            name='dark_store_address',
            field=models.CharField(default='Plot 12, Main Ring Road, Indore, Madhya Pradesh 452001', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderdeliverytracking',
            name='dark_store_lat',
            field=models.FloatField(default=22.7196),
        ),
        migrations.AlterField(
            model_name='orderdeliverytracking',
            name='dark_store_lng',
            field=models.FloatField(default=75.8577),
        ),
        migrations.AlterField(
            model_name='orderdeliverytracking',
            name='dark_store_name',
            field=models.CharField(default='Om Super Mart Express Hub #4 - Indore', max_length=150),
        ),
        migrations.AlterField(
            model_name='orderdeliverytracking',
            name='rider_vehicle',
            field=models.CharField(default='Ather 450X Electric (MP-09-BF-4892)', max_length=100),
        ),
    ]
