# Generated by Django 5.2.1 on 2026-09-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderdeliverytracking_customer_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliverytracking',
            name='is_live_tracking_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdeliverytracking',
            name='partner_access_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='orderdeliverytracking',
            name='rider_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdeliverytracking',
            name='rider_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdeliverytracking',
            name='rider_name',
            field=models.CharField(default='Damodar Vaishnav', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdeliverytracking',
            name='rider_phone',
            field=models.CharField(default='+91 90220 54562', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderdeliverytracking',
            name='rider_rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='orderdeliverytracking',
            name='rider_vehicle',
            field=models.CharField(default='Electric Delivery Scooter (MP-09)', max_length=100),
        ),
    ]
