# Generated by Django 5.2.1 on 2026-09-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='UPC, EAN-13, or custom product barcode', max_length=64, null=True, unique=True),
        ),
    ]
